# Default values for metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# config is the MetalLB configuration, in YAML format. Refer to
# https://metallb.universe.tf/configuration/ for available options.
config:

# load-balancers. When arpCIDR is specified instead of config, the
# chart will install a trivial "quick start" MetalLB configuration
# that uses ARP mode. Refer to https://metallb.universe.tf/ for more
# information. For production configurations, use of the `config`
# field is recommended instead of arpCIDR.
arpCIDR:

# createRBAC specifies whether to install and use RBAC rules.
createRBAC: true

# controller contains configuration specific to the MetalLB cluster
# controller.
controller:
  image:
    repository: metallb/controller
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

# controller contains configuration specific to the MetalLB speaker
# daemonset.
speaker:
  image:
    repository: metallb/speaker
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
