# Default values for metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

arpCIDR:
config:

rbac:
  create: true

controller:
  image:
    repository: metallb/controller
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

speaker:
  image:
    repository: metallb/speaker
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
