language: go
go_import_path: go.universe.tf/metallb
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
script:
- glide install
- go install -v go.universe.tf/metallb/controller go.universe.tf/metallb/speaker
- go test $(glide novendor)
- go test -race $(glide novendor)
- go vet $(glide novendor)
- glide novendor | xargs -n1 golint
os:
- linux
go:
- 1.8.x
- 1.9.x
- 1.10beta1
jobs:
  include:
  - stage: deploy
    if: type = push
    go: 1.9.x
    install: true
    script: true
    deploy:
    - provider: script
      script: go run dockerfiles/trigger_build.go
      on:
        all_branches: true
  - stage: deploy
    if: type = push
    go: 1.9.x
    install: true
    script: true
    deploy:
    - provider: script
      script: go run dockerfiles/trigger_build.go
      on:
        tags: true
  - stage: test on tip
    go: tip

env:
  global:
  - secure: MS9luk0gu4nwbiecMrzo/uThfu/a0xbMAtkOvWIkYnVZ7tc/nV6Y0SLGUe2DgrgpF2ONSChTZvFjcQvM0PrhI8R4o3gMGl+P9NlbG1LlTBN6N4fkqEDgQRThTZTxRaioGbWXv2cxJUjen+VKhNkW0qKCe9dU3R0EiZJAKYiPkDhf53f1ecvCZ1lIS7OTBrA/doi8vT+LFEUep6w8fCOFDeyj+wqDS1YkI4qzJ32ROOr/kgDTbEzfum6fXvg+Z0yx1HkcAd7LyupN/stw748tMf8NvDdyIoptgt0T5iEriMgbHE1KCRGvaczDezXy5nabsGJCs7nnevfj5xA8/T6J44dHr0OxncLJwPMc2S51PnWH9RqKCN6bR/KL0LWaywTzrBp/PIn70BWRZ4wlGPpoSUPfpqjK633Ju7RwGob8fwx6Mh684WJcMfenXsl1e5bjuArO3dNTJZ5veeGi3/eOBzjH/z/Bn5DxJZHW7J2paZ8TPvHu3HEZ0284H+U007FqhbC568ZD196Jueb5vKL3WTiAJYEeBqx+FCIzKENRmVZ5eOR5ZrSTd8jMkuLwAZ+kaIDUYUgtx88UC85ZrZ1Sm0rHBq1f01uI+Pq7HojFzinQtLS3Lkq3AONbfkj7ps3sCCaCRvfZh5lmvuuSo4IjM5g1fti/RQDQyTOwmr1f7EU=
  - secure: kb+VMhSWXdQiTrklg660Q2MhVUEPYwDYX/w3R+p2lSqfhq/O1xIiQN/JICNacRjys9pCojKnOsY0/bAIUUmrBJUOYG4RwSH1id+tgtn8pmHMU5RT1xe9M0fj//7+wZTmsecXcWUXJHxfD0T7bRmhBACktrlKfuYKgKjAUvS9lRVLnzk02+MBZ9s6dVoomJTiiBzMom+7Hiyk8EHGkvL60ZwLNRGKZQdoZrodf699xTvGMrIK8G6+CGcZvO9CorRYpQuRJbX30k32hr6cXljuF6xVsImQy3tcUpj5R6L5FNzXB+ee/pqX1jog/K1+gyu/8mSwlPVLU9vpoDehfvy9E3wXHBZdsF/4YP9/KqVLeH6MDQ7ccYVY4Le0ubc6d2mkXdGsPnHiuFpAsL1qpa3vplnOzsvPq6MVtxSLPIUQI0mcetdxKWjoAGUIQQQPn7gP6tyA5GMEggKUcaxAfKBe0Xy/0unUj/emJvOmSJouXYHZhz2r+KT5emBPp70pfs8CwwoucVYsTuBTn3TY2pdCHTR0hpmp4Ud5uC/ugNW6TRTcu43UYqw8PCERdRGJ/GQbJcM9p4oSYLQKNJ0n8eM85Kx6n0gew6dTOG7KHHIdfuN9KmFK9/UqDvqUG8zzUMKWvib2zh4WFmquQHWmIHx6sUiaqbZF+5bM7dvfhNArYiU=
  - secure: hdXrwjsQauNQ4WIgPlKxQf4hOwZ77b5C9Zkt1DVH71wYvDSmM9MAuydNh7ppHz2koPeKLACaMhUhjNoutmCeZtRikdNPPnDP1mfXxq6JlomSJYjzitUjTjgiODxV1V0YvH3MplwEhIS0H7eyn1wsAUXHqrPljKDLbJoQ4bshpj6bhBS5Oy+cSh7cTCYPIjsJ4OkXydtLVVgF0YbrRfnhTM7UQ2USxCYHnrSnZ2KvF8UrVq5DP0auZbUhKJ0iwyPKcEhcu73cShSiKICjXFOR/EFrnickloRRa2kjxTAJ6YG9LBv1hXA7s4Z5kidciI9NzM3JK1xlwTq1r+WoI+453lp3aR1lzXu0NfzEyBvr/wwo8ab/Qhg2zLP9BhH5Yo3aLJIh60k8s/yL/afcsWyBP3c71gtwZeZXIx4ahTRpm+E1iAaBZfI0MiukRkT++kpYk7JE2pW0OPhfWRlQJr5JTWErNX47LcZAXU4xDEiCyoZNjcLJxXk0Bj1w6152wNPKskjfbCBE5c/aow+2l+JDicq14mop2GZpHTDxtrm7lzpd0KIGN0TXtVFQnFjePLi4qOuiVl+I6bh6jgqlEy9l9CU9luxePjRRH7cJALH8ZOsFIqVZb0G27bimLwh5HPmyAknkQn74iRlHHjgwJ9uFTYrbzMyFXesztb2wFqqE8jg=
