# -*- mode: yaml -*-

version: 2
jobs:
  test-1.8:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: make ci-prepare
      - run: make ci-build
      - run: make ci-test
      - run: make ci-lint
  test-1.9:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: make ci-prepare
      - run: make ci-build
      - run: make ci-test
      - run: make ci-lint
  test-1.10beta1:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.10beta1
    steps:
      - checkout
      - run: make ci-prepare
      - run: make ci-build
      - run: make ci-test
      - run: make ci-lint
  deploy-controller:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make ci-prepare
      - run: make gen-image-targets TAG=${CIRCLE_BRANCH:-${CIRCLE_TAG}} REGISTRY=metallb
      - run: make -f Makefile.image-targets controller
  deploy-speaker:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make ci-prepare
      - run: make gen-image-targets TAG=${CIRCLE_BRANCH:-${CIRCLE_TAG}} REGISTRY=metallb
      - run: make -f Makefile.image-targets speaker
  deploy-test-bgp-router:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make ci-prepare
      - run: make gen-image-targets TAG=${CIRCLE_BRANCH:-${CIRCLE_TAG}} REGISTRY=metallb
      - run: make -f Makefile.image-targets test-bgp-router
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-1.8:
          filters:
            tags:
              only: /.*/
      - test-1.9:
          filters:
            tags:
              only: /.*/
      - test-1.10beta1:
          filters:
            tags:
              only: /.*/
      - deploy-controller:
          filters:
            tags:
              only: /.*/
          requires:
            - test-1.8
            - test-1.9
      - deploy-speaker:
          filters:
            tags:
              only: /.*/
          requires:
            - test-1.8
            - test-1.9
      - deploy-test-bgp-router:
          filters:
            tags:
              only: /.*/
          requires:
            - test-1.8
            - test-1.9
