# -*- mode: yaml -*-

version: 2
jobs:
  test-1.11:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
      - run: curl -L https://git.io/vp6lP | sh # gometalinter
      - run: go test ./controller ./speaker ./internal/...
      - run: go test -race ./controller ./speaker ./internal/...
      - run: gometalinter --deadline=5m --disable-all --enable=gofmt --enable=vet --enable=vetshadow --enable=structcheck --enable=unconvert --vendor ./...
      - run: cp manifests/metallb.yaml manifests/metallb.yaml.prev
      - run: go run make.go -a helm
      - run: diff -u manifests/metallb.yaml.prev manifests/metallb.yaml
      - run: rm manifests/metallb.yaml.prev
  deploy-controller:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $CIRCLE_BRANCH
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: go get github.com/estesp/manifest-tool
      - run: go run make.go --action build,image,push --arch all --binary controller --tag ${CIRCLE_BRANCH:-${CIRCLE_TAG}} --registry metallb --multiarch
  deploy-speaker:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $CIRCLE_BRANCH
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: go get github.com/estesp/manifest-tool
      - run: go run make.go --action build,image,push --arch all --binary speaker --tag ${CIRCLE_BRANCH:-${CIRCLE_TAG}} --registry metallb --multiarch
  deploy-test-bgp-router:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $CIRCLE_BRANCH
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: go get github.com/estesp/manifest-tool
      - run: go run make.go --action build,image,push --arch all --binary test-bgp-router --tag ${CIRCLE_BRANCH:-${CIRCLE_TAG}} --registry metallb --multiarch
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-1.11:
          filters:
            tags:
              only: /.*/
      - deploy-controller:
          filters:
            branches:
              ignore: /pull\/.*/
            tags:
              only: /.*/
          requires:
            - test-1.11
      - deploy-speaker:
          filters:
            branches:
              ignore: /pull\/.*/
            tags:
              only: /.*/
          requires:
            - test-1.11
      - deploy-test-bgp-router:
          filters:
            branches:
              ignore: /pull\/.*/
            tags:
              only: /.*/
          requires:
            - test-1.11
