# -*- mode: yaml -*-

version: 2
jobs:
  test-1.12:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: sudo apt-get install python-pip
      - run: sudo pip install invoke semver pyyaml
      - run: echo "export GO111MODULE=on" >>$BASH_ENV
      - run: curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
      - run: curl -L https://git.io/vp6lP | sh # gometalinter
      - run: go test -short ./...
      - run: go test -short -race ./...
      - run: PATH=./bin:$PATH gometalinter --deadline=5m --disable-all --enable=gofmt --enable=vet --vendor ./...
      - run: cp manifests/metallb.yaml manifests/metallb.yaml.prev
      - run: inv helm
      - run: diff -u manifests/metallb.yaml.prev manifests/metallb.yaml
      - run: rm manifests/metallb.yaml.prev
  deploy-controller:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get install python-pip
      - run: sudo pip install invoke semver pyyaml
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: go get github.com/estesp/manifest-tool # Can't fetch this with modules yet :(
      - run: echo "export GO111MODULE=on" >>$BASH_ENV
      - run: inv push-multiarch --binaries=controller --tag=${CIRCLE_BRANCH:-${CIRCLE_TAG}} --docker-user=metallb
  deploy-speaker:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get install python-pip
      - run: sudo pip install invoke semver pyyaml
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: go get github.com/estesp/manifest-tool # Can't fetch this with modules yet :(
      - run: echo "export GO111MODULE=on" >>$BASH_ENV
      - run: inv push-multiarch --binaries=speaker --tag=${CIRCLE_BRANCH:-${CIRCLE_TAG}} --docker-user=metallb
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-1.12:
          filters:
            tags:
              only: /.*/
      - deploy-controller:
          filters:
            branches:
              ignore: /pull\/.*/
            tags:
              only: /.*/
          requires:
            - test-1.12
      - deploy-speaker:
          filters:
            branches:
              ignore: /pull\/.*/
            tags:
              only: /.*/
          requires:
            - test-1.12
