version: 2
jobs:
  test-1.8:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: make ci-prepare
      - run: make ci-build
      - run: make ci-test
      - run: make ci-lint
  test-1.9:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: make ci-prepare
      - run: make ci-build
      - run: make ci-test
      - run: make ci-lint
  test-1.10beta1:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.10beta1
    steps:
      - checkout
      - run: make ci-prepare
      - run: make ci-build
      - run: make ci-test
      - run: make ci-lint
  deploy:
    working_directory: /go/src/go.universe.tf/metallb
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD quay.io
      - run: make ci-deploy TAG=$CIRCLE_BRANCH REGISTRY=quay.io/metallb
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-1.8
      - test-1.9
      - test-1.10beta1
      - deploy:
          requires:
            - test-1.8
            - test-1.9
