# -*- mode: yaml -*-

version: 2
jobs:
  test-1.13:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python3-pip
      - run: sudo pip3 install invoke semver pyyaml
      - run: inv test
      - run: cp manifests/metallb.yaml manifests/metallb.yaml.prev
  lint-1.13:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: curl -L https://git.io/vp6lP | sh # gometalinter
      - run: PATH=./bin:$PATH gometalinter --deadline=5m --disable-all --enable=gofmt --enable=vet --vendor ./...
  publish-images:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update && sudo apt-get install -y python-pip
      - run: pip install invoke semver pyyaml
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: mkdir -p ./bin
      - run: wget -O ./bin/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64 && chmod +x ./bin/manifest-tool
      - run: PATH=./bin:$PATH inv push-multiarch --binaries=controller --binaries=speaker --registry=docker.io --repo=metallb --tag=${CIRCLE_BRANCH:-${CIRCLE_TAG}}
  publish-images-quay:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update && sudo apt-get install -y python-pip
      - run: pip install invoke semver pyyaml
      - run: docker login quay.io -u $QUAY_USER -p $QUAY_PASSWORD
      - run: mkdir -p ./bin
      - run: wget -O ./bin/manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64 && chmod +x ./bin/manifest-tool
      - run: PATH=./bin:$PATH inv push-multiarch --binaries=controller --binaries=speaker --registry=quay.io --repo=metallb --tag=${CIRCLE_BRANCH:-${CIRCLE_TAG}}
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test-1.13:
          filters:
            tags:
              only: /.*/
      - lint-1.13:
          filters:
            tags:
              only: /.*/
      - publish-images:
          filters:
            branches:
              only:
                - main
                - /v.*/
            tags:
              only: /.*/
          requires:
            - test-1.13
            - lint-1.13
      - publish-images-quay:
          filters:
            branches:
              only:
                - main
                - /v.*/
            tags:
              only: /.*/
          requires:
            - test-1.13
            - lint-1.13
