apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
{{- if .Values.config }}
{{ toYaml .Values.override_config | indent 4 }}
{{- else if .Values.arpCIDR }}
    address-pools:
    - name: default
      protocol: arp
      cidr:
      - {{ .Values.arpCIDR }}
{{- else }}
    # No configuration defined, MetalLB will not do anything useful.
{{- end }}
