apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  namespace: metallb-system
  name: speaker
  labels:
    {{- if .Values.helmLabels }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- end }}
    app: {{ template "metallb.name" . }}
    component: speaker
spec:
  selector:
    matchLabels:
      app: {{ template "metallb.name" . }}
      component: speaker
      {{- if .Values.helmLabels }}
      release: {{ .Release.Name | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- if .Values.helmLabels }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        {{- end }}
        app: {{ template "metallb.name" . }}
        component: speaker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7472"
    spec:
{{- if .Values.rbac.create }}
      serviceAccountName: speaker
{{- end }}
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
      - name: speaker
        image: {{ .Values.speaker.image.repository }}:{{ .Values.speaker.image.tag }}
        imagePullPolicy: {{ .Values.speaker.image.pullPolicy }}
        args:
        - --port=7472
        env:
        - name: METALLB_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: monitoring
          containerPort: 7472
        resources:
{{ toYaml .Values.speaker.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - all
            add:
            - net_raw
